### ISSUE TITLE
screensaver?

### ISSUE THREAD

**Issue by kapet** [rspier/chrome-stream-deck#3]
When there is no meeting running, the stream deck now still shows some buttons and the clock.

Is there a risk of burnin? (The internet suggests that is at least a risk for older versions of the large stream deck, don't know about the mini.)

Could the Chrome extension just black out the buttons after some time without meeting?

**Comment by rspier** [comment]
This was more complicated than expected.

I did two things:

1. For the cases when we're still on meet.google.com, and the extension is running (because it only runs on meet.google.com as it injects itself into the page), look for the "More options" menu. This only shows up on a call or in the green room.  If the menu isn't there, don't paint anything and keep the buttons black.
2. Attempt to handle the unload/beforeunload events and clear the buttons.  This works *sometimes*.  It looks (i.e. I speculate) that if go from meet.google.com to a non-google domain, the JS interpreter gets destroyed pretty quickly, so the handler doesn't have time to run.  Another theory is that Meet or Chrome is over-eagerly closing the USB device, so we can't send any last commands.
